name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17.0.1+12
        distribution: 'temurin'
  
  
  docker-image:
  
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Refresh versions
        run: ./gradlew refreshVersions
      - name: Build docker image
        run: docker build . --file Dockerfile -t app
      - name: Run postgres
        run: docker run -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=salon --name postgres -h postgres postgres
      - name: Run app
        run: docker run -d -p 8200:8200 --name app --link postgres app
        
      
  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1+12
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test
