name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17.0.1+12
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x gradlew  
    - name: Clean
      run: ./gradlew clean build -x jar
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/libs/*.jar
  
  
  docker-image:
  
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v2
      - name: a
        run: pwd
      - name: b
        run: ls -la /home/runner/work/microservice/microservice/artifact
      - name: Build docker image
        run: docker build --build-arg JAR_FILE=/home/runner/work/microservice/microservice/artifact . --file Dockerfile -t app
      - name: Run postgres
        run: docker run -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=salon --name postgres -h postgres postgres
      - name: Run app
        run: docker run -p 8200:8200 --name app --link postgres app
        
      
  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1+12
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test
